### ISSUE TITLE
Blender 2.8 compatibility

### ISSUE THREAD

**Issue by dentsoft-foundation** [dentsoft-foundation/linkSlicerBlender#1]
Interface does not appear in the "N" menu of Blender 2.8 when the add-on is loaded.

**Comment by talmazov** [comment]
Adjusted add-on to reflect changes in Blender 2.8 API as such:
- bl_info now reflect blender 2.80
- bpy.context.user_preferences (2.7) -> bpy.context.preferences (2.8)
- bpy.types.material.diffuse_color is now a float array of 4 items, mat.diffuse_color = (red_v, grn_v, blu_v, alpha_v)
- bpy.data.groups (2.7) -> bpy.data.collections (2.8)
- bpy.types.Object.to_mesh(preserve_all_data_layers=False, depsgraph=None) (2.8) 
- bpy.app.handlers.scene_update_post (2.7) -> bpy.app.handlers.depsgraph_update_post (2.8)
- bl_region_type no longer accepts 'TOOLS' now it is 'UI'
- meshes.remove() no longer supported in 2.8 -> Object.to_mesh_clear()

References:
- https://blenderartists.org/t/2-80-cheat-sheet-for-updating-add-ons/1148974
- https://devtalk.blender.org/t/porting-my-addons-to-2-8-missing-scene-update-post-handler/2465/9
- https://docs.blender.org/api/blender2.8/bpy.types.Object.html?highlight=to_mesh#bpy.types.Object.to_mesh
- https://docs.blender.org/api/current/bpy.types.Material.html#bpy.types.Material
- https://github.com/godotengine/godot-blender-exporter/pull/215
